<?php

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'phone' => '7771234567',
                'usertype' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 1,
            ],
            [
                'name' => 'Кенжебеков Нуржан Кенжебекович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'kenzhebekov.nurzhan888@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 25,
            ],
            [
                'name' => 'Сагнаев Арман',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'armansagnayev@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 23,
            ],
            [
                'name' => 'Алтаев Данияр',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'daniyaraltayev@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 20,
            ],
            [
                'name' => 'Уранхаев Нурлан Тельманович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'uranhayev.nurlan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 26,
            ],
            [
                'name' => 'Смагулов Аян',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'smagulov.ayan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 11,
            ],[
                'name' => 'Кушеров Асхат',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'kusherov.ashat@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 2,
            ],
            [
                'name' => 'Алтаева Жулдыз Канатовна',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'altayeva_zhuldiz@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 19,
            ],
            [
                'name' => 'Абаев Анзор',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'anzor4eh4@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 17,
            ],
            [
                'name' => 'Бесбаева Гульнар',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'besbayeva.gulnar@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 1,
            ],
            [
                'name' => 'Баймаханов Аскер',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'baimahanov_asker@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 4,
            ],
            [
                'name' => 'Макашева Айгуль',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'zhakupova.aigul01@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 7,
            ],
            [
                'name' => 'Акатаев Руслан',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'akatayev_ruslan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 8,
            ],
            [
                'name' => 'Шаяхметова Бибигуль',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'shayahmetova_bibigul@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 5,
            ],
            [
                'name' => 'Макатай Азат',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'makatai_azat@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 6,
            ],
            [
                'name' => 'Жакупова Айгуль Ильясовна',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'zhakupova.ai@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 18,
            ],
            [
                'name' => 'Ескендирова Махаббат',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'yeskendirova.m@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 9,
            ],
            [
                'name' => 'Санабаева Альмира',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'sanbayevaalmira@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 21,
            ],
            [
                'name' => 'Аяпова Альбина',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'ayapova.albina@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 22,
            ],
            [
                'name' => 'Сабыркулов Асылбек Тулемисович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'sabyrkulov.asylbek@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 23,
            ],
            [
                'name' => 'Серикбаев Нурхан Жандосович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'serikbayev.nurhan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 10,
            ],
            [
                'name' => 'Аяпбергенов Султан Зейнуллович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'ayapbergenov.sultan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 12,
            ],
            [
                'name' => 'Алкуатова Сауле Алкуатовна',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'alkuatova.saule@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 13,
            ],
            [
                'name' => 'Жакупов Руслан Ергалиевич',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'zhakupov.ruslan01@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 14,
            ],
            [
                'name' => 'Балабеков Бауржан Жаксылыкович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'balabekov.baurzhan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 15,
            ],
            [
                'name' => 'Ғалымжан Нұрәділ Болатұлы',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'galymzhan.nuradil@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 16,
            ],
            [
                'name' => 'Тажбен Ерсаин Ерғалиұлы',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'tazhben.yersayin@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 3,
            ],
            [
                'name' => 'Жанбыршы Алмас Маликович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'Zhanbyrshy7@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 24,
            ],


        ]);


    }
}
