<?php

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('users')->insert([
            [
                'first_name' => 'Admin',
                'sur_name' => 'Admin',
                'middle_name' => 'Admin',
                'phone' => '7771234567',
                'usertype' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 1,
            ],
            [
                'first_name' => 'Айгерим',
                'sur_name' => 'Альмурзаева',
                'middle_name' => '',
                'phone' => '7074295539',
                'usertype' => 'admin',
                'email' => 'a.almurzayeva@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 1,
            ],
            [
                'first_name' => 'Жәнібек',
                'sur_name' => '',
                'middle_name' => 'Кенжебекұлы',
                'phone' => '7074295539',
                'usertype' => 'admin',
                'email' => 'Quaresma90@list.ru',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 1,
            ],
            [
                'first_name' => 'Нуржан',
                'sur_name' => 'Кенжебеков',
                'middle_name' => 'Кенжебекович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'kenzhebekov.nurzhan888@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 25,
            ],
            [
                'sur_name' => 'Сагнаев',
                'first_name' => 'Арман',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'armansagnayev@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 23,
            ],
            [
                'sur_name' => 'Алтаев',
                'first_name' => 'Данияр',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'daniyaraltayev@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 20,
            ],
            [
                'sur_name' => 'Уранхаев',
                'first_name' => 'Нурлан',
                'middle_name' => 'Тельманович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'uranhayev.nurlan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 26,
            ],
            [
                'sur_name' => 'Смагулов',
                'first_name' => 'Аян',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'smagulov.ayan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 11,
            ],[
                'sur_name' => 'Кушеров',
                'first_name' => 'Асхат',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'kusherov.ashat@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 2,
            ],
            [
                'sur_name' => 'Алтаева',
                'first_name' => 'Жулдыз',
                'middle_name' => 'Канатовна',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'altayeva_zhuldiz@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 19,
            ],
            [
                'sur_name' => 'Абаев',
                'first_name' => 'Анзор',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => 'admin',
                'email' => 'anzor4eh4@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 17,
            ],
            [
                'sur_name' => 'Бесбаева',
                'first_name' => 'Гульнар',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'besbayeva.gulnar@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 1,
            ],
            [
                'sur_name' => 'Баймаханов',
                'first_name' => 'Аскер',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'baimahanov_asker@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 4,
            ],
            [
                'sur_name' => 'Макашева',
                'first_name' => 'Айгуль',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'zhakupova.aigul01@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 7,
            ],
            [
                'sur_name' => 'Акатаев',
                'first_name' => 'Руслан',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'akatayev_ruslan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 8,
            ],
            [
                'sur_name' => 'Шаяхметова',
                'first_name' => 'Бибигуль',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'shayahmetova_bibigul@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 5,
            ],
            [
                'sur_name' => 'Макатай',
                'first_name' => 'Азат',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'makatai_azat@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 6,
            ],
            [
                'sur_name' => 'Жакупова',
                'first_name' => 'Айгуль',
                'middle_name' => 'Ильясовна',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'zhakupova.ai@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 18,
            ],
            [
                'sur_name' => 'Ескендирова',
                'first_name' => 'Махаббат',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'yeskendirova.m@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 9,
            ],
            [
                'sur_name' => 'Санабаева',
                'first_name' => 'Альмира',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'sanbayevaalmira@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 21,
            ],
            [
                'sur_name' => 'Аяпова',
                'first_name' => 'Альбина',
                'middle_name' => '',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'ayapova.albina@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 22,
            ],
            [
                'sur_name' => 'Сабыркулов',
                'first_name' => 'Асылбек',
                'middle_name' => 'Тулемисович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'sabyrkulov.asylbek@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 23,
            ],
            [
                'sur_name' => 'Серикбаев',
                'first_name' => 'Нурхан',
                'middle_name' => 'Жандосович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'serikbayev.nurhan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 10,
            ],
            [
                'sur_name' => 'Аяпбергенов',
                'first_name' => 'Султан',
                'middle_name' => 'Зейнуллович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'ayapbergenov.sultan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 12,
            ],
            [
                'sur_name' => 'Алкуатова',
                'first_name' => 'Сауле',
                'middle_name' => 'Алкуатовна',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'alkuatova.saule@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 13,
            ],
            [
                'sur_name' => 'Жакупов',
                'first_name' => 'Руслан',
                'middle_name' => 'Ергалиевич',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'zhakupov.ruslan01@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 14,
            ],
            [
                'sur_name' => 'Балабеков',
                'first_name' => 'Бауржан',
                'middle_name' => 'Жаксылыкович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'balabekov.baurzhan@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 15,
            ],
            [
                'sur_name' => 'Ғалымжан',
                'first_name' => 'Нұрәділ',
                'middle_name' => 'Болатұлы',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'galymzhan.nuradil@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 16,
            ],
            [
                'sur_name' => 'Тажбен',
                'first_name' => 'Ерсаин',
                'middle_name' => 'Ерғалиұлы',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'tazhben.yersayin@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 3,
            ],
            [
                'sur_name' => 'Жанбыршы',
                'first_name' => 'Алмас',
                'middle_name' => 'Маликович',
                'phone' => '7771234567',
                'usertype' => Null,
                'email' => 'Zhanbyrshy7@gmail.com',
                'password' => Hash::make('123'),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'role_id' => 24,
            ],


        ]);


    }
}
